### ISSUE TITLE
New feature - app.InsertCurrentId

### ISSUE THREAD

**Issue by teohz** [adziok/obsidian-incremental-id#1]
Would it be possible to add another option to add the current ID value after increasing it?
i.e. to use in the front matter:

id: <% await app.insertIncrementalId('{prefix}') %>
aliases: <% await app.insertCurrentId('{prefix}') %>

If possible one could just reference the current ID after increasing it in the templates.

**Comment by adziok** [comment]
Hi, I will see what I can do in the next week. I'm hoping it will be fairly simple but we'll see what the api will allow me to do!

**Comment by adziok** [comment]
Added in 0.3.0
