### ISSUE TITLE
[FR] Leading zeros

### ISSUE THREAD

**Issue by a13ph** [adziok/obsidian-incremental-id#2]

**Comment by adziok** [comment]
Hi, can you describe what exactly you mean?

**Comment by miu007** [comment]
I also want this feature. My understanding, it is like starting with A-001 instead of A-1. 

This way, the sorting would not rank A-2 before A-10. 

It will rank A-010 before A-002.

**Comment by miu007** [comment]
It will rank A-010 before A-002.

**Comment by miu007** [comment]
By the way, great job of making the plugin.

**Comment by miu007** [comment]
At the same time, can you also add a feature to choose the linkage symbol? By default it uses '-'. Is it possible to use others such as "_" or " " or even without any? I have some previous notes that uses other than "-" and I want to be consistent. Thanks very much in advance!

**Comment by adziok** [comment]
I will add your suggestions this year :D

**Comment by adziok** [comment]
Done
